# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DXPPQADvS9EtbECb_lv4Z3MLmC_P-gHO
"""

name = input("이름을 입력하세요:")
stu_num = input("학번을 입력하세요:")
major = input("학과를 입력하세요:")
grade = input("학년을 입력하세요:")

print("이름:", name)
print("학번:", stu_num)
print("학과:", major)
print("학년:", grade)